### ISSUE TITLE
Database not pushing to/pulling from Github for collaboration

### ISSUE THREAD

**Issue by alodes999** [alodes999/07-22-project-warmup#1]
After doing the first part of the warmup (getting the first table/model/controller set up and running), I pushed the project up so Ciprianna could do the next portion (the next table etc).  When she tried to run `rake db:migrate` to add the new migration, she got an ActiveRecord error:

``` ruby
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "project_warmup_development" does not exist

PG::ConnectionBad: FATAL:  database "project_warmup_development" does not exist

Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

How can we push/pull the development db to use for building, or is the only way to do this to work through our heroku collab?

**Comment by sumeetjain** [comment]
Typically, the database itself is not shared.

Ciprianna needs to `rake db:create` and then run migrations to get the schema loaded. _Content_ needs to be re-created on each machine though.

(You can look into Rails Seeds if you want certain content created for all machines though.)
