### ISSUE TITLE
Heroku does not like us (again)

### ISSUE THREAD

**Issue by alodes999** [alodes999/07-22-project-warmup#2]
We are having issues where any route attempt to our tasks routes (users/:user_id/tasks and the like) sends back a 500 status and a "We're sorry, but something went wrong" and "Check your logs" message.  Our logs however show no ruby error messages or anything else, just the 500 status line for the routes.  Using a puts statement does return to our logs (we used a puts to verify it wasn't a BCrypt error like we had before, and BCrypt returns a correct hash). 

Locally we have no issues getting into any of our routes, including the routes heroku is returning 500 on.  

Is there any place to find a particular error message outside of the logs, or a command that can parse further into what is happening?

**Comment by sumeetjain** [comment]
Can you add `gem 'rails_12factor', group: :production` to your Gemfile (and run `bundle install`) and redeploy? I'm hoping that fixes the issue with the logs on Heroku not showing anything useful.
